title: URGeo Android App
theme: jekyll-theme-cayman
description: Aplicación para seguir los contactos de personas positivas a covid-19
show_downloads: true
github:
  is_project_page: false
  zip_url: https://github.com/nmlemus/android_covid_tracking_app/blob/gh-pages/urgeo.apk
  another_url: https://github.com/goblob/android_covid/blob/master/docs/urgeo.apk
